// 都道府県のマッピングを定義
const prefectureMap: { [key: string]: string } = {
  "Hokkaido Prefecture": "北海道",
  "Aomori Prefecture": "青森県",
  "Iwate Prefecture": "岩手県",
  "Miyagi Prefecture": "宮城県",
  "Akita Prefecture": "秋田県",
  "Yamagata Prefecture": "山形県",
  "Fukushima Prefecture": "福島県",
  "Ibaraki Prefecture": "茨城県",
  "Tochigi Prefecture": "栃木県",
  "Gunma Prefecture": "群馬県",
  "Saitama Prefecture": "埼玉県",
  "Chiba Prefecture": "千葉県",
  "Tokyo Prefecture": "東京都",
  "Kanagawa Prefecture": "神奈川県",
  "Niigata Prefecture": "新潟県",
  "Toyama Prefecture": "富山県",
  "Ishikawa Prefecture": "石川県",
  "Fukui Prefecture": "福井県",
  "Yamanashi Prefecture": "山梨県",
  "Nagano Prefecture": "長野県",
  "Gifu Prefecture": "岐阜県",
  "Shizuoka Prefecture": "静岡県",
  "Aichi Prefecture": "愛知県",
  "Mie Prefecture": "三重県",
  "Shiga Prefecture": "滋賀県",
  "Kyoto Prefecture": "京都府",
  "Osaka Prefecture": "大阪府",
  "Hyogo Prefecture": "兵庫県",
  "Nara Prefecture": "奈良県",
  "Wakayama Prefecture": "和歌山県",
  "Tottori Prefecture": "鳥取県",
  "Shimane Prefecture": "島根県",
  "Okayama Prefecture": "岡山県",
  "Hiroshima Prefecture": "広島県",
  "Yamaguchi Prefecture": "山口県",
  "Tokushima Prefecture": "徳島県",
  "Kagawa Prefecture": "香川県",
  "Ehime Prefecture": "愛媛県",
  "Kochi Prefecture": "高知県",
  "Fukuoka Prefecture": "福岡県",
  "Saga Prefecture": "佐賀県",
  "Nagasaki Prefecture": "長崎県",
  "Kumamoto Prefecture": "熊本県",
  "Oita Prefecture": "大分県",
  "Miyazaki Prefecture": "宮崎県",
  "Kagoshima Prefecture": "鹿児島県",
  "Okinawa Prefecture": "沖縄県",
};

// 英語名から日本語名を取得する関数
export function getJapanesePrefectureName(englishName: string): string {
  return prefectureMap[englishName] || "未知の都道府県";
}

